version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: pg_bottlen
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bottlen
      TZ: Asia/Seoul

    ports:
      - '5432:5432'

    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis_bottlen
    restart: unless-stopped

    environment:
      TZ: Asia/Seoul

    ports:
      - '6379:6379' # Redis core
      # - '8001:8001' # RedisInsight UI

    volumes:
      - ./redis_data:/data
